config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get 'home/index'
  resources:events
  resources :shared_events, only: [:edit, :show, :update],  param: :uuid
  
  # /events/1/guests/new
  # params[:event_id]
  resources :events do
    resources :guests, only: [:new, :create]
    resources :attendances, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  extend Enumerize
  enumerize :entry, in: {ok: 1, neutral: 2, ng: 3}
  
  belongs_to :user
  belongs_to :guest
  belongs_to :event_schedule
  
end

app/models/event.rb
class Event < ApplicationRecord
  has_secure_token :uuid

  has_many :guests, through: :events_guest
  has_many :events_guests
  has_many :attendances
  has_many :event_schedules, dependent: :destroy
  accepts_nested_attributes_for :event_schedules, allow_destroy: true
  belongs_to :user

  validates :title, presence: true  
  validates :content, presence: true
end

app/models/event_schedule.rb
class EventSchedule < ApplicationRecord
  belongs_to :event
end

app/models/events_guest.rb
class EventsGuest < ApplicationRecord
  belongs_to :event
  belongs_to :guest
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :event, through: :events_guest
  has_many :events_guest
  has_many :post, dependent: :destroy
  has_many :attendances, dependent: :destroy
  
  validates :name, presence: true 
  validates :email, email: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :guest
  
  validates :content, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :events, dependent: :destroy
  has_many :post,   dependent: :destroy
  has_many :attendances, dependent: :destroy
  
  validates :name, presence: true  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_event
  before_action :set_guest
  
  def new
    @attendance = @guest.attendance.build
    @event_schedules = @event.event_schedules.order
  end
  
  def create
    @attendance = @guest.attendance.build(attendance_params)
    if @attendance.save
      redirect_to shared_event_path(@event.uuid)
    else
      render :new
    end
  end
  
  private
    def set_event
      @event = Event.find(params[:event_id])
    end
    
    def set_guest
      @guest = Guest.find_by(browser_uuid: session[:browser_uuid]) unless user_signed_in?
    end
    
    def attendance_params
      params.require(:attendance).permit(:entry, :comment)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :show, :update, :destroy]
    
  def index
    @events = current_user.events.all
  end
  
  def new
    @event = current_user.events.build
    @event_schedule = @event.event_schedules.build
  end
  
  def show
    @event_schedules = @event.event_schedules
  end
  
  def edit
  end
  
  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "成功！"
      redirect_to @event
    else
      render :new
    end
  end
  
  def destroy
    @event.destroy!
    redirect_to root_url
  end
  
  def update
    if @event.update_attributes(event_params)
      flash[:success] = "更新！"
      redirect_to @event
    else
      render :edit
    end
  end
  
  
  private
  
    def set_event
      @event = current_user.events.find(params[:id])
    end
    
    def event_params
      params.require(:event).permit(:title, :content, :target_at, event_schedules_attributes: [:id, :targer_at, :_destroy])
    end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_event
  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)
    browser_uuid = SecureRandom.uuid
    session[:browser_uuid] = browser_uuid
    @guest.browser_uuid = browser_uuid
    if @guest.save
      redirect_to shared_event_path(@event.uuid)
    else
      render :new
    end
  end
  
  private
    def set_event
      @event = Event.find(params[:event_id])
    end
    
    def guest_params
      params.require(:guest).permit(:name, :comment, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shared_events_controller.rb
class SharedEventsController < ApplicationController
  before_action :set_shared_event, only: [:show, :edit, :update]
  before_action :set_guest
    
  def show
    if !@guest.present? && !user_signed_in?
      redirect_to new_event_guest_path(@shared_event.id)
    end
    @event_schedules = @shared_event.event_schedules
  end
    
  def edit
  end
    
  def update
    if @shared_event.update(event_params)
      redirect_to @shared_event
    else
      render :edit
    end
  end

  private
    def set_shared_event
      @shared_event = Event.find_by!(uuid: params[:uuid])
    end
    
    def set_guest
      @guest = Guest.find_by(browser_uuid: session[:browser_uuid]) unless user_signed_in?
    end
        
    def shared_event_params
      params.require(:event).permit(:title, :content, :target_at)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shared_events_helper.rb
module SharedEventsHelper
end

app/views/attendances/new.html.erb
<h1>出席ページ</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  
    <%= form_for @attendance do |f| %> <!--:url => {:action => :create}-->
    
      <%= f.label "コメント" %>
      <%= f.text_area :comment, class: 'form-control' %>
      
      <% @event_schedules.each do |es| %>
        <p><%= f.label es.targer_at %></p>
        <p><%= f.select :entry, Attendance.entry.options %></p>
      <% end %>
      
      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/events/_event_schedule_fields.html.erb
<div class="nested-fields">
  <%= f.label "開催予定日" %>
  <%= f.date_select :targer_at %>
  <%= link_to_remove_association "削除", f %>
</div>

app/views/events/_form.html.erb
<div>
  <div class="col-md-6 col-md-offset-3">
  
    <%= form_for @event do |f| %>
      <%= render 'layouts/error_messages' %>
    
      <%= f.label "タイトル" %>
      <%= f.text_field :title, class: 'form-control' %>
      
    　<%= f.label "内容" %>
      <%= f.text_area :content, class: 'form-control' %>
      
      <%= f.fields_for :event_schedules do |event_schedule| %>
        <%= render "event_schedule_fields", f: event_schedule %>
      <%end%>
      
      <div id="links">
        <%= link_to_add_association "追加", f, :event_schedules %>
      </div>
      
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/events/edit.html.erb
<% provide(:button_text, "更新") %>
<h1>編集</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h1>イベント一覧</h1>

<div class="event-card">
  <%= link_to "新しいイベントを企画する", new_event_path, class: "btn-outline-secondary new" %>

<% @events.each do |event| %>
  <div class="card event-index">
    <div class="card-header">
      <%= event.target_at %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= event.title %></h5>
      <p class="card-text"><%= event.content %></p>
      <%= link_to "SHOW", event, class: "btn btn-outline-secondary btn-sm" %>
      <%= link_to "編集", edit_event_path(event.id), class: "btn btn-outline-secondary btn-sm" %>
      <%= link_to '削除', event, class: "btn btn-outline-secondary btn-sm", method: :delete,
                                     data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>
  <%= link_to "新しいイベントを企画する", new_event_path, class: "btn-outline-secondary" %>
</div>

app/views/events/new.html.erb
<% provide(:button_text, "登録") %>
<h1>イベント企画</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<h1>events/show</h1>

<div class="event-card">
  <p>URL: <%= link_to  shared_event_url(@event.uuid), shared_event_url(@event.uuid),
     class: "btn btn-outline-secondary btn-sm" %></p>

  <div class="card">
    <div class="card-header">
      <h4><%= @event.title %></h4>
    </div>
    
    <div class="card-body">
      <% if @event.target_at.nil? %>
        <p>開催日：未定</p>
      <% else %>
        <p>開催日：<%= @event.target_at %></p>
      <% end %>
      <p class="card-text"><%= @event.content %></p>
      
      <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">開催予定日</li>
          <% @event_schedules.each do |e| %>
            <li class="list-group-item"><%= e.targer_at %></li>
          <% end %>
        </ul>
      </div>
      
      <%= link_to "イベント一覧", events_path, class: "btn btn-outline-secondary btn-sm" %>
      <%= link_to "編集", edit_event_path(@event.id), class: "btn btn-outline-secondary btn-sm" %>
    </div>
  </div>
</div>

app/views/guests/new.html.erb
<h1>ログイン</h1>

<%= form_for @guest,:url => {:action => :create} do |f| %>
  <%= f.label "名前" %>
  <%= f.text_field :name, class: 'form-control' %>
  
  <%= f.label "email" %>
  <p><%= f.text_field :email, class: 'form-control' %>
  
  <%= f.label "comment" %>
  <%= f.text_field :comment, class: 'form-control' %>
  
  <%= f.submit "決定", class: "btn btn-primary" %>
<% end %>

app/views/home/index.html.erb
<div class="center jumbotron">
  <h1 class="home__title">イベントを企画しよう！</h1>
  
  <% if user_signed_in? %>
    <p><%= current_user.name %>さん、ようこそ！</p>
    <%= link_to "イベント一覧", events_path, class: "btn btn-lg btn-primary" %>
  <% else %>
  　<h2>イベント企画のお手伝いします</h2>
    <p>ログインまたは新規登録をしてください。</p>
    <%= link_to "ログイン", new_user_session_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "新規登録", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <% end %>

</div>

app/views/layouts/_error_messages.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@task.errors.count, "error") %>.
    </div>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-dark bg-dark">
  <nav class="navbar navbar-expand-lg header__navigation">
    <%= link_to "EVENT_APP", root_path, id: "logo" %>
    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav header__list">
        <li class="nav-item header__list-item"><%= link_to "Home",   root_path %></li>
          <% if user_signed_in? %>
            <li class="nav-item header__list-item"><%= link_to "イベント一覧", events_path %></li>
            <li class="nav-item header__list-item"><%= link_to current_user.email, edit_user_registration_path %></li>
            <li class="nav-item header__list-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="nav-item header__list-item"><%= link_to "新規登録", new_user_registration_path %></li>
            <li class="nav-item header__list-item"><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>      
        </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/sample_tasks.erb
<h1><%= current_user.email %>さんのタスク</h1>

<div id="search">
  <%= search_form_for @search do |f| %>
    <p>
      <%= f.label :title_or_content_cont,"タイトル、内容から検索:  " %>
      <%= f.search_field :title_or_content_cont %>
      <%= f.submit "検索", class: "actions"  %>
    </p>
  <% end %>
    
  <%= search_form_for @search do |f| %>
    <p>
      <%= f.label :deadline_at_lteq ,"期限が〇〇までのタスク:  " %>
      <%= f.date_select :deadline_at_lteq %>
      <%= f.submit "検索", class: "actions" %>
    </p>
  <% end %>

    
  <% if @tasks.any? %>

<h2>検索結果タスク</h2>
<table class="table table-striped ">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">期限</th>
      <th scope="col">内容</th>
      <th scope="col">進行状況</th>
      <th scope="col">
        <%= form_tag(tasks_path, method: :get) do %>
			 		<%= select_tag :priority, options_for_select({low: 0, middle: 1, high: 2}), id: 'priority', prompt: '優先順位' %>
					<%= submit_tag 'sort' %>
				<% end %>
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, task, class: "btn-outline-secondary" %></td>
        <td><%= task.deadline_at.strftime('%Y/%m/%d') %></td>
        <td><%= task.content %></td>
        <td>
          
          <%= form_tag(tasks_path, method: :get) do %>
					  <%= select_tag :status, options_for_select({waiting: 0, working: 1, done: 2}), 
					                 id: 'status', prompt: task.status %>
				  <% end %>
				</td>
				<td>
				  <%= select_tag :priority, options_for_select({low: 0, middle: 1, high: 2}),
				                  id: 'deadline', prompt: task.priority %>
				</td>
        <td><%= link_to '編集', edit_task_path(task.id), class: "btn-outline-secondary" %></td>
        <td><%= link_to '削除', task, class: "btn-outline-secondary", method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks %>

  <% else%>
    <p class="not-result">その検索では見つかりませんでした。</p>
    
    <h2>タスク一覧</h2>
      <table class="table table-striped ">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">期限</th>
      <th scope="col">内容</th>
      <th scope="col">進行状況</th>
      <th scope="col">
        <%= form_tag(tasks_path, method: :get) do %>
			 		<%= select_tag :priority, options_for_select({low: 0, middle: 1, high: 2}), id: 'priority', prompt: '優先順位' %>
					<%= submit_tag '優先順位ソート' %>
				<% end %>
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, task, class: "btn-outline-secondary" %></td>
        <td><%= task.deadline_at.strftime('%Y/%m/%d') %></td>
        <td><%= task.content %></td>
        <td>
          
          <%= form_tag(tasks_path, method: :get) do %>
					  <%= select_tag :status, options_for_select({waiting: 0, working: 1, done: 2}), 
					                 id: 'status', prompt: task.status %>
				  <% end %>
				</td>
				<td>
				  <%= select_tag :priority, options_for_select({low: 0, middle: 1, high: 2}),
				                  id: 'deadline', prompt: task.priority %>
				</td>
        <td><%= link_to '編集', edit_task_path(task.id), class: "btn-outline-secondary" %></td>
        <td><%= link_to '削除', task, class: "btn-outline-secondary", method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <% end %>
  <%= link_to "新しいタスクを追加する", new_task_path, class: "btn-outline-secondary" %>

</div>

app/views/shared_events/edit.html.erb
<h1>編集</h1>

app/views/shared_events/show.html.erb
<!--確認用-->
<% if !user_signed_in? %>
<%= @guest.name %>
<% end %>

<h1><%= @shared_event.title %></h1>
<h2><%= @shared_event.content %></h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">日程</th>
      <th scope="col">〇</th>
      <th scope="col">△</th>
      <th scope="col">×</th>
    </tr>
  </thead>
  
  <tbody>
    <% @event_schedules.each do |es| %>
      <tr>
        <th scope="row"><%= es.targer_at %></th>
        <td>〇.count</td>
        <td>△.count/td>
        <td>×.count</td>
      </tr>
    <% end %>
  </tbody>
</table>